name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - '*'

jobs:
  testsuite:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.2', '7.4', '8.0']
        
       
         
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        ini-values: apc.enable_cli = 1
        coverage: pcov
     
    - name: see PHP
      run: 
          echo ${{ matrix.php-version }}
          
    - name: Composer install
      run: | 
          composer update 
          composer install
    
   
    - name: Run PHPUnit
      run: |       
       if [[ ${{ matrix.php-version }} == '7.4' ]]; then
           export CODECOVERAGE=1 && vendor/bin/phpunit --verbose --coverage-clover=coverage.xml
        else
          vendor/bin/phpunit
        fi
   
    - name: Code Coverage Report
      if: matrix.php-version == '7.4' 
      uses: codecov/codecov-action@v1
