name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - '*'

jobs:
  testsuite:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.2', '7.4']
       
        
    steps:
    - uses: actions/checkout@v2
     
    - name: Composer install
      run: | 
          composer update 
          composer install
    
   
    - name: Run PHPUnit
      run: |     
          vendor/bin/phpunit
