name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - '*'

jobs:
  testsuite:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.2', '7.4']
       
         
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
     
    - name: see PHP
      run: 
          echo ${{ matrix.php-version }}
    - name: Composer install
      run: | 
          composer update 
          composer install
    
   
    - name: Run PHPUnit
      run: |     
          vendor/bin/phpunit
